# Generated by Django 5.2.8 on 2025-12-01 18:43

import apps.repositorio.models.repositorio
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Área Temática')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Área Temática',
                'verbose_name_plural': 'Áreas Temáticas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo do Autor')),
                ('lattes_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Lattes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Projeto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_public', models.BooleanField(default=True, verbose_name='É público?')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Palavra-chave / Tag')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tag / Palavra-chave',
                'verbose_name_plural': 'Tags / Palavras-chave',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo do Documento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo da Publicação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Publicação',
                'verbose_name_plural': 'Tipos de Publicação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subprojeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Subprojeto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subprojetos', to='repositorio.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Subprojeto',
                'verbose_name_plural': 'Subprojetos',
                'ordering': ['projeto', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=2000, verbose_name='Título')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo / Abstract')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data da Publicação')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN (International Standard Book Number)')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=apps.repositorio.models.repositorio.item_file_path, verbose_name='Arquivo')),
                ('link_externo', models.URLField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Link Externo/URL')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data da ultima atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('area_tematica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas_tematicas', to='repositorio.areatematica', verbose_name='Área Temática')),
                ('autores', models.ManyToManyField(related_name='autores', to='repositorio.autor', verbose_name='Autores')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('usuario_ultima_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Última Atualização')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='repositorio.status', verbose_name='Status de Publicação')),
                ('subprojeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subprojetos', to='repositorio.subprojeto', verbose_name='Subprojeto')),
                ('tags', models.ManyToManyField(related_name='tags', to='repositorio.tag', verbose_name='Palavras-chave')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_documentos', to='repositorio.tipodocumento', verbose_name='Tipo de Documento')),
                ('tipo_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_publicacaoes', to='repositorio.tipopublicacao', verbose_name='Veículo de Publicação')),
            ],
            options={
                'verbose_name': 'Registro / Documento',
                'verbose_name_plural': 'Registros / Documentos',
                'ordering': ['-data_publicacao', 'titulo'],
            },
        ),
    ]
