# Generated by Django 5.2.8 on 2026-02-27 02:49

import apps.repositorio.models.repositorio
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('imagem', models.ImageField(upload_to=apps.repositorio.models.repositorio.gallery_image_path, verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criacao')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data da ultima atualizacao')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos_galeria_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Criacao')),
                ('usuario_ultima_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos_galeria_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario da Ultima Atualizacao')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['ordem', '-date_create'],
            },
        ),
    ]
