# Generated by Django 5.2.8 on 2026-04-28 18:52

import apps.repositorio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_fotogaleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='isbn',
            field=models.CharField(blank=True, help_text='Insira o ISBN-10 ou ISBN-13', max_length=20, null=True, unique=True, validators=[apps.repositorio.validators.validate_isbn], verbose_name='ISBN (International Standard Book Number)'),
        ),
    ]
