# Generated by Django 5.2.8 on 2026-04-29 14:52

import apps.repositorio.models.repositorio
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositorio", "0003_alter_registro_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="arquivo",
            field=models.FileField(
                blank=True,
                max_length=5000,
                null=True,
                upload_to=apps.repositorio.models.repositorio.item_file_path,
                verbose_name="Arquivo",
            ),
        ),
    ]
