# Generated by Django 5.2.8 on 2026-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_alter_registro_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='especie_informacoes',
            field=models.CharField(blank=True, help_text='Informe nome científico e/ou quantidade de espécimes quando aplicável.', max_length=500, null=True, verbose_name='Nome científico e/ou quantidade'),
        ),
        migrations.AddField(
            model_name='registro',
            name='especie_nova',
            field=models.BooleanField(default=False, verbose_name='Registro relacionado a espécies novas?'),
        ),
    ]
