# Generated by Django 5.2.8 on 2026-09-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0006_alter_subprojeto_nome'),
        ('repositorio', '0006_subareatematica_registro_subareas'),
    ]

    operations = [
    ]
