# Generated by Django 5.2.8 on 2026-10-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_merge_20260914_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='area_tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='repositorio.areatematica', verbose_name='Área Temática'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='autores',
            field=models.ManyToManyField(related_name='registros', to='repositorio.autor', verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='repositorio.status', verbose_name='Status de Publicação'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='subprojeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='repositorio.subprojeto', verbose_name='Subprojeto'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tags',
            field=models.ManyToManyField(related_name='registros', to='repositorio.tag', verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='repositorio.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='repositorio.tipopublicacao', verbose_name='Veículo de Publicação'),
        ),
    ]
